/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMediumRouteImport } from './routes/api/medium'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediumRoute = ApiMediumRouteImport.update({
  id: '/api/medium',
  path: '/api/medium',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/api/medium': typeof ApiMediumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/api/medium': typeof ApiMediumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work': typeof WorkRoute
  '/api/medium': typeof ApiMediumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work' | '/api/medium'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work' | '/api/medium'
  id: '__root__' | '/' | '/work' | '/api/medium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkRoute: typeof WorkRoute
  ApiMediumRoute: typeof ApiMediumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medium': {
      id: '/api/medium'
      path: '/api/medium'
      fullPath: '/api/medium'
      preLoaderRoute: typeof ApiMediumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkRoute: WorkRoute,
  ApiMediumRoute: ApiMediumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
